# Generated by Django 5.0.7 on 2024-08-09 17:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_tweet_no_of_likes_alter_tweet_id_liketweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liketweet',
            name='id_tweet',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
