# Generated by Django 5.0.7 on 2024-08-10 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0006_remove_liketweet_id_tweet_liketweet_tweet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
